import { controllerLabel, formatPercent, formatStat, titleCase } from '../lib/format';

const COLUMNS = [
  ['Success rate', (s) => formatPercent(s.success_rate)],
  ['Steps', (s) => formatStat(s.steps)],
  ['Path length', (s) => formatStat(s.path_length)],
  ['Path efficiency', (s) => formatStat(s.path_efficiency)],
  ['Collisions', (s) => formatStat(s.collisions)],
  ['Energy %', (s) => formatStat(s.energy_consumed)],
  ['Charging', (s) => formatStat(s.charging_events)],
  ['Reward', (s) => formatStat(s.total_reward)],
];

/**
 * Comparison tables generated by the evaluation scripts.
 *
 * Values are mean ± 95% confidence interval over the episodes that entered the
 * average; "n/a" means no episode qualified (for example path efficiency when
 * nothing was ever delivered).
 */
export default function ResultsTable({ results }) {
  if (!results?.length) {
    return (
      <section className="results">
        <h2>Experimental results</h2>
        <p className="muted">
          No result files found. Generate them with{' '}
          <code>python -m baselines.evaluate_baselines --scenario default</code>.
        </p>
      </section>
    );
  }

  return (
    <section className="results">
      <h2>Experimental results</h2>
      {results.map((result) => (
        <article key={result.id} className="result-card">
          <header>
            <h3>{titleCase(result.scenario)}</h3>
            <span className="muted small">
              {result.id}
              {result.generatedAt ? ` · generated ${result.generatedAt}` : ''}
            </span>
          </header>
          <div className="table-scroll">
            <table>
              <thead>
                <tr>
                  <th>Controller</th>
                  <th>Episodes</th>
                  {COLUMNS.map(([label]) => (
                    <th key={label}>{label}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {result.summaries.map((summary) => (
                  <tr key={summary.controller}>
                    <td>{controllerLabel(summary.controller)}</td>
                    <td>
                      {summary.n_successful}/{summary.n_episodes}
                    </td>
                    {COLUMNS.map(([label, accessor]) => (
                      <td key={label}>{accessor(summary)}</td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </article>
      ))}
    </section>
  );
}
